export const FETCH_MASTER_LINE_ITEMS_LOADING = 'FETCH_MASTER_LINE_ITEMS_LOADING';
export const FETCH_MASTER_LINE_ITEMS_SUCCESS = 'FETCH_MASTER_LINE_ITEMS_SUCCESS';
export const FETCH_MASTER_LINE_ITEMS_ERROR = 'FETCH_MASTER_LINE_ITEMS_ERROR';

export const FETCH_MORE_MASTER_LINE_ITEMS_LOADING = 'FETCH_MORE_MASTER_LINE_ITEMS_LOADING';
export const FETCH_MORE_MASTER_LINE_ITEMS_SUCCESS = 'FETCH_MORE_MASTER_LINE_ITEMS_SUCCESS';
export const FETCH_MORE_MASTER_LINE_ITEMS_ERROR = 'FETCH_MORE_MASTER_LINE_ITEMS_ERROR';