export const FETCH_ORDER_LIST_LOADING = "FETCH_ORDER_LIST_LOADING";
export const FETCH_ORDER_LIST_SUCCESS = "FETCH_ORDER_LIST_SUCCESS";
export const FETCH_ORDER_LIST_ERROR = "FETCH_ORDER_LIST_ERROR";

export const FETCH_ORDER_LINE_ITEMS_LOADING = "FETCH_ORDER_LINE_ITEMS_LOADING";
export const FETCH_ORDER_LINE_ITEMS_SUCCESS = "FETCH_ORDER_LINE_ITEMS_SUCCESS";
export const FETCH_ORDER_LINE_ITEMS_ERROR = "FETCH_ORDER_LINE_ITEMS_ERROR";

export const ADD_ORDER_LINE_ITEM_LOADING = "ADD_ORDER_LINE_ITEM_LOADING";
export const ADD_ORDER_LINE_ITEM_SUCCESS = "ADD_ORDER_LINE_ITEM_SUCCESS";
export const ADD_ORDER_LINE_ITEM_ERROR = "ADD_ORDER_LINE_ITEM_ERROR";

export const SET_CURRENT_SELECTED_ORDER_ID = "SET_CURRENT_SELECTED_ORDER_ID";

export const HIDE_ORDER_LINE_ITEMS_STATE = "HIDE_ORDER_LINE_ITEMS_STATE";

export const RESET_ORDER_LIST_STATE = "RESET_ORDER_LIST_STATE";