export const FETCH_ORDER_LIST_LOADING = "FETCH_ORDER_LIST_LOADING";
export const FETCH_ORDER_LIST_SUCCESS = "FETCH_ORDER_LIST_SUCCESS";
export const FETCH_ORDER_LIST_ERROR = "FETCH_ORDER_LIST_ERROR";

export const RESET_ORDER_LIST_STATE = "RESET_ORDER_LIST_STATE";